apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: teamtwo-namespace
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'