apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-lms-storage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /app/data  # Update this path as per your cluster's configuration
